from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "generated"


def copy_file(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def copy_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    shutil.copytree(
        src,
        dst,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(".git", ".venv", "__pycache__", "*.pyc"),
    )


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    copy_file(ROOT / "README.md", OUT / "index.md")
    copy_file(ROOT / "ARCHITECTURE.md", OUT / "project" / "architecture.md")

    root_docs = {
        "CHARTER.md": "charter.md",
        "DESIGN_PHILOSOPHY.md": "design-philosophy.md",
        "TENETS.md": "tenets.md",
        "NON_GOALS.md": "non-goals.md",
        "DECISIONS.md": "decisions.md",
        "ROADMAP.md": "roadmap.md",
        "CONTRIBUTING.md": "contributing.md",
        "CODE_OF_CONDUCT.md": "code-of-conduct.md",
        "CHANGELOG.md": "changelog.md",
    }
    for src_name, dst_name in root_docs.items():
        copy_file(ROOT / src_name, OUT / "project" / dst_name)

    copy_tree(ROOT / "standard", OUT / "standards")
    copy_tree(ROOT / "reference", OUT / "reference-houses")
    copy_tree(DOCS / "adr", OUT / "adr")
    copy_tree(DOCS / "project", OUT / "project")
    copy_tree(DOCS / "workflows", OUT / "workflows")
    copy_tree(DOCS / "checklists", OUT / "checklists")
    copy_tree(DOCS / "images", OUT / "images")

    for name in ("disclaimer.md", "reference-options.md", "repository-map.md", "tech-stack.md"):
        copy_file(DOCS / name, OUT / "project" / name)

    (OUT / ".generated").write_text(
        "Generated by scripts/build_docs.py. Do not edit directly.\n",
        encoding="utf-8",
    )
    print(f"Generated documentation sources at {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
