#!/usr/bin/env bash
set -euo pipefail

# setup-generated-docs-pipeline.sh
# Keeps canonical sources outside docs/ and generates docs/generated/ for MkDocs.

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "[!] Run this script inside the repository."
  exit 1
fi

mkdir -p scripts docs/generated

cat > scripts/build_docs.py <<'PY'
from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "generated"


def copy_file(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def copy_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    shutil.copytree(
        src,
        dst,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(".git", ".venv", "__pycache__", "*.pyc"),
    )


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    copy_file(ROOT / "README.md", OUT / "index.md")
    copy_file(ROOT / "ARCHITECTURE.md", OUT / "project" / "architecture.md")

    root_docs = {
        "CHARTER.md": "charter.md",
        "DESIGN_PHILOSOPHY.md": "design-philosophy.md",
        "TENETS.md": "tenets.md",
        "NON_GOALS.md": "non-goals.md",
        "DECISIONS.md": "decisions.md",
        "ROADMAP.md": "roadmap.md",
        "CONTRIBUTING.md": "contributing.md",
        "CODE_OF_CONDUCT.md": "code-of-conduct.md",
        "CHANGELOG.md": "changelog.md",
    }
    for src_name, dst_name in root_docs.items():
        copy_file(ROOT / src_name, OUT / "project" / dst_name)

    copy_tree(ROOT / "standard", OUT / "standards")
    copy_tree(ROOT / "reference", OUT / "reference-houses")
    copy_tree(DOCS / "adr", OUT / "adr")
    copy_tree(DOCS / "project", OUT / "project")
    copy_tree(DOCS / "workflows", OUT / "workflows")
    copy_tree(DOCS / "checklists", OUT / "checklists")
    copy_tree(DOCS / "images", OUT / "images")

    for name in ("disclaimer.md", "reference-options.md", "repository-map.md", "tech-stack.md"):
        copy_file(DOCS / name, OUT / "project" / name)

    (OUT / ".generated").write_text(
        "Generated by scripts/build_docs.py. Do not edit directly.\n",
        encoding="utf-8",
    )
    print(f"Generated documentation sources at {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
PY

if [[ -f mkdocs.yml ]]; then
  cp mkdocs.yml mkdocs.yml.before-generated-docs
  echo "[+] Backed up mkdocs.yml"
fi

cat > mkdocs.yml <<'YAML'
site_name: Open Housing Standard
site_description: Open, vendor-neutral housing standards and reference designs
repo_url: https://github.com/OpenHousingStandard/open-housing-standard
repo_name: OpenHousingStandard/open-housing-standard

docs_dir: docs/generated
site_dir: site

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Standards:
      - Overview: standards/README.md
      - OHS-000 — Editorial Standard:
          - Overview: standards/OHS-000/README.md
          - Style: standards/OHS-000/STYLE.md
          - Specification Template: standards/OHS-000/TEMPLATE.md
          - Chapter Template: standards/OHS-000/CHAPTER-TEMPLATE.md
          - Document Lifecycle: standards/OHS-000/DOCUMENT-LIFECYCLE.md
          - Changelog: standards/OHS-000/CHANGELOG.md
      - OHS-001 — Open Housing Standard:
          - Overview: standards/OHS-001/README.md
          - 1. Introduction: standards/OHS-001/01-introduction.md
          - 2. Scope: standards/OHS-001/02-scope.md
          - 3. Normative References: standards/OHS-001/03-normative-references.md
          - 4. Terminology: standards/OHS-001/04-terminology.md
          - 5. Design Principles: standards/OHS-001/05-design-principles.md
          - 6. Standard Architecture: standards/OHS-001/06-standard-architecture.md
          - 7. Conformance: standards/OHS-001/07-conformance.md
          - 8. Governance: standards/OHS-001/08-governance.md
          - 9. Versioning: standards/OHS-001/09-versioning.md
          - Appendix A: standards/OHS-001/appendix-a.md
          - Appendix B: standards/OHS-001/appendix-b.md
      - OHS-100 — Architectural Rules: standards/OHS-100/README.md
      - OHS-200 — Technical Core: standards/OHS-200/README.md
      - OHS-300 — Universal Design: standards/OHS-300/README.md
      - OHS-400 — Energy & Sustainability: standards/OHS-400/README.md
      - OHS-500 — Documentation & Digital Assets: standards/OHS-500/README.md
      - OHS-600 — Reference Houses: standards/OHS-600/README.md
      - OHS-700 — Compliance & Certification: standards/OHS-700/README.md
      - OHS-900 — Glossary: standards/OHS-900/README.md

  - Reference Houses:
      - Overview: reference-houses/README.md
      - OH90: reference-houses/oh90/README.md
      - OH120: reference-houses/oh120/README.md
      - OH150: reference-houses/oh150/README.md

  - ADRs:
      - Index: adr/index.md
      - ADR-0001 — Open Formats: adr/0001-open-formats.md
      - ADR-0002 — RFC-style Documents: adr/0002-rfc-style-standard-documents.md
      - ADR-0003 — Three Reference Sizes: adr/0003-three-reference-sizes.md
      - ADR-0004 — Editorial Standard: adr/0004-editorial-standard.md

  - Project:
      - Architecture: project/architecture.md
      - Charter: project/charter.md
      - Design Philosophy: project/design-philosophy.md
      - Tenets: project/tenets.md
      - Non-goals: project/non-goals.md
      - Decisions: project/decisions.md
      - Roadmap: project/roadmap.md
      - Repository Map: project/repository-map.md
      - Technology Stack: project/tech-stack.md
      - Disclaimer: project/disclaimer.md

  - Workflows:
      - Open Design Workflow: workflows/open-design-workflow.md

  - Checklists:
      - Design Checklist: checklists/design-checklist.md
      - Handover Documentation: checklists/handover-documentation.md
YAML

touch .gitignore
grep -qxF "docs/generated/" .gitignore || printf "\n# Generated documentation staging tree\ndocs/generated/\n" >> .gitignore
grep -qxF "site/" .gitignore || printf "site/\n" >> .gitignore

cat > scripts/build-docs.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"
uv run python scripts/build_docs.py
uv run mkdocs build --strict
SH
chmod +x scripts/build-docs.sh

echo "[*] Generating documentation..."
uv run python scripts/build_docs.py

echo "[*] Running strict MkDocs build..."
uv run mkdocs build --strict

echo
echo "[✓] Generated documentation pipeline is ready."
echo
echo "Use:"
echo "  ./scripts/build-docs.sh"
echo
echo "Then:"
echo "  git status"
echo "  git diff --stat"
echo "  git add -A"
echo '  git commit -m "Add generated MkDocs documentation pipeline"'
echo "  git push origin $(git branch --show-current)"
